import React from "react";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

const Header = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>

      <header className="flex items-center justify-between font-bellefair">
        <Image
          src="/images/logo.svg"
          alt="logo"
          width="32"
          height="32"
          className="ml-8"
        ></Image>

        <div className="hidden">
          <Image
            src="/images/hamburger.svg"
            alt="open-menu"
            width="32"
            height="32"
          ></Image>
        </div>

        <ul className="flex gap-[4vw] bg-space-white/5 py-12 px-8">
          <li className="">
            <Link href="#" className="hover:text-gray-200 hover:underline underline-offset-[3.2rem] decoration-2">
              HOME
            </Link>
          </li>
          <li>
            <Link href="#" className="hover:text-gray-200 hover:underline underline-offset-[3.2rem] decoration-2">DESTIONATION</Link>
          </li>
          <li>
            <Link href="#" className="hover:text-gray-200 hover:underline underline-offset-[3.2rem] decoration-2">CREW</Link>
          </li>
          <li>
            <Link href="#" className="hover:text-gray-200 hover:underline underline-offset-[3.2rem] decoration-2">TECHNOLOGY</Link>
          </li>
        </ul>
      </header>
    </>
  );
};

export default Header;
