import React from "react";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

const Header = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>
      <header className="flex justify-center gap-4">
        <Image src="/images/logo.svg" alt="logo" width="32" height="32"></Image>
        <div>
          <Link href="#">00 HOME</Link>
          <Link href="#">01 DESTIONATION</Link>
          <Link href="#">02 CREW</Link>
          <Link href="#">03 TECHNOLOGY</Link>
        </div>
      </header>
    </>
  );
};

export default Header;
